### ISSUE TITLE
Make trix-editor scrollable

### ISSUE THREAD

**Issue by Dineshs91** [Dineshs91/devlog#153]
Add the below to fix this issue.

``` css
.log.content {
    overflow-y: scroll;
    min-height: 23em;
    max-height: 25em;
}
```
